"""Sudoers management for ptop3 privileged subscripts."""
import os
import pwd
import shutil
import subprocess
import sys
import tempfile

SUDOERS_FILE = "/etc/sudoers.d/ptop3"

_SCRIPTS = {
    "ptop3-drop-caches": "drop_caches",
    "ptop3-swap-clean": "swap_clean",
}


def _find_script_path(console_script_name: str) -> str | None:
    """Return the absolute path to an installed console script, or None."""
    return shutil.which(console_script_name)


def check_sudo() -> dict[str, str]:
    """Check whether ptop3 subscripts have NOPASSWD sudo access.

    Returns a dict mapping script name to one of:
      "ok"             — sudo -n works
      "missing"        — script not found in PATH
      "needs_password" — script found but sudo requires a password
      "error"          — other subprocess error
    """
    result: dict[str, str] = {}
    for name in _SCRIPTS:
        path = _find_script_path(name)
        if path is None:
            result[name] = "missing"
            continue
        proc = subprocess.run(
            ["sudo", "-n", path, "--help"],
            capture_output=True,
            text=True,
        )
        if proc.returncode == 0:
            result[name] = "ok"
        elif "password" in (proc.stderr or "").lower() or proc.returncode == 1:
            result[name] = "needs_password"
        else:
            result[name] = "error"
    return result


def _build_sudoers_content(username: str, paths: dict[str, str]) -> str:
    lines = ["# ptop3 privileged subscripts — generated by ptop3 --init-subscripts"]
    for name, path in paths.items():
        lines.append(f"{username} ALL=(root) NOPASSWD: {path}")
    return "\n".join(lines) + "\n"


def init_subscripts() -> None:
    """Write /etc/sudoers.d/ptop3 with NOPASSWD entries for subscripts.

    If running as root, writes the file directly and validates with visudo.
    If not root, prints detailed instructions.
    """
    paths: dict[str, str] = {}
    missing = []
    for name in _SCRIPTS:
        path = _find_script_path(name)
        if path:
            paths[name] = path
        else:
            missing.append(name)

    if missing:
        print(
            f"Warning: the following scripts were not found in PATH: {', '.join(missing)}\n"
            f"Run 'pip install ptop3' and ensure the install bin directory is in PATH.",
            file=sys.stderr,
        )

    username = pwd.getpwuid(os.getuid()).pw_name
    content = _build_sudoers_content(username, paths)

    if os.geteuid() == 0:
        _write_as_root(content)
    else:
        _print_howto(username, content)


def _write_as_root(content: str) -> None:
    """Write and validate the sudoers file."""
    # Write to a temp file, validate, then move into place
    fd, tmp_path = tempfile.mkstemp(prefix="ptop3_sudoers_", dir="/tmp")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.chmod(tmp_path, 0o440)

        # Validate with visudo
        result = subprocess.run(
            ["visudo", "-c", "-f", tmp_path],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            print(f"error: visudo validation failed:\n{result.stderr}", file=sys.stderr)
            return

        # Move into place
        import shutil as _shutil
        _shutil.move(tmp_path, SUDOERS_FILE)
        os.chmod(SUDOERS_FILE, 0o440)
        print(f"Written: {SUDOERS_FILE}")
        print("Sudo configuration complete.")
    except Exception as e:
        print(f"error: {e}", file=sys.stderr)
        try:
            os.unlink(tmp_path)
        except OSError:
            pass


def _print_howto(username: str, content: str) -> None:
    """Print instructions for manually creating the sudoers file."""
    print("Not running as root. To configure passwordless sudo for ptop3 subscripts:")
    print()
    print("Option 1 — run as root:")
    print("  sudo ptop3 --init-subscripts")
    print()
    print("Option 2 — manual setup:")
    print(f"  sudo tee {SUDOERS_FILE} << 'EOF'")
    print(content.rstrip())
    print("EOF")
    print(f"  sudo chmod 440 {SUDOERS_FILE}")
    print(f"  sudo visudo -c -f {SUDOERS_FILE}")
    print()
    print("Option 3 — interactive editor:")
    print(f"  sudo visudo -f {SUDOERS_FILE}")
    print("  # Then add the following lines:")
    for line in content.splitlines():
        if not line.startswith("#"):
            print(f"  {line}")
